name: auxilia_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  http: ^1.4.0
  flutter_dotenv: ^5.2.1
  file_picker: ^8.0.0+1
  audioplayers: ^5.2.1
  speech_to_text: ^6.6.0
  geolocator: ^10.1.0
  url_launcher: ^6.2.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  
  # ✅ Configuración de assets (imágenes y fuentes)
  assets:
    - lib/assets/AuxilIA.png  # Ajusta la ruta según donde esté tu imagen
    # - assets/images/  # Opcional: si tienes más imágenes en esta carpeta

  fonts:
    - family: CarterOne
      fonts:
        - asset: assets/fonts/CarterOne-Regular.ttf  # Descarga la fuente y colócala aquí