name: auxilia_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  http: ^1.4.0
  flutter_dotenv: ^5.2.1
  file_picker: ^10.1.9  # Versión más estable para web
  audioplayers: ^6.4.0
  speech_to_text: ^7.0.0
  geolocator: ^14.0.1
  url_launcher: ^6.2.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  
  # ✅ Configuración de assets (imágenes y fuentes)
  assets:
    - assets/imagenes/Auxilia.png  # Ruta exacta y completa
    - assets/imagenes/logo.png  
    - assets/imagenes/logohorizontal.png   # Agrega todas las imágenes necesarias
    # O si prefieres incluir toda la carpeta:
    # - lib/assets/imagenes/  

  fonts:
    - family: CarterOne
      fonts:
        - asset: assets\fonts\Carter_One\CarterOne-Regular.ttf  # Descarga la fuente y colócala aquí